---
#Create ec2 instance
- name: Ansible test
  hosts: localhost
  gather_facts: False
  vars:
      region: us-east-1                         # Name of region
      instance_type: t2.micro                   # Type of EC2 server to create
      ami: ami-09e67e426f25ce0d7                # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
      keypair: ansible_instance                 # Key pair name as written in AWS consol
      subnetid: subnet-19145f7f                 # Subnet ID
      count: 2                                  # How many ec2 instance create
      security_group: ansible_securitygroup     # Name for SecureGroup

  tasks:
  - name: Create secure group with port 22,80,443,8080 open 0.0.0.0/0
    ec2_group:
      name: "{{security_group}}"
      description: Secure group for Servers with port 22,80,443,8080
      region: "{{region}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0  
  
  - name: Create an ec2 instance
    ec2:
      key_name: "{{ keypair }}"
      group: "{{security_group}}"
      instance_type:  "{{ instance_type }}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      instance_tags: 
        name: AnsibleDeploment
        type: AnsibleEC2DevOps
      count: " {{count}} "  
      vpc_subnet_id: "{{subnetid}} "
      assign_public_ip: yes     
    register: ec2

  - name: Add host to group buildapp
    add_host:
      name: "{{ ec2.instances[0].public_ip }}"
      groups: buildapp
    with_items: "{{ ec2.instances }}"

  - name: Add host to group prod
    add_host:
      name: "{{ ec2.instances[1].public_ip }}"
      groups: prod
    with_items: "{{ ec2.instances }}"
  
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22 
      state: started 
    with_items: "{{ ec2.instances }}"

  

#Build server
- name: Build app
  hosts: buildapp
  become: yes
  tasks: 
    - name: Update repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install default-jdk git maven
      apt:
        pkg: 
          - default-jdk
          - git
          - maven

    - name: Download project from github
      git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
       dest: /tmp/boxfuse-sample-java-war-hello/
    - name: build app maven
      command: mvn package
      args:
       chdir: /tmp/boxfuse-sample-java-war-hello/

    - name: Copy .war file from remote host to local host
      synchronize:  src={{ item }} dest=/tmp/ mode=pull
      with_items:
       - "/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war"

#Prod server
- name: Run buildapp hello-1.0.war
  hosts: prod
  become: yes
  tasks: 
    - name: Update repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install default-jdk tomcat
      apt:
        pkg:
          - default-jdk
          - tomcat9

    - name: Copy .war from local host to remote host
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
    
